### ISSUE TITLE
Cortex-M0+ device header has no MPU defined

### ISSUE THREAD

**Issue by VladimirUmek** [ARM-software/Cortex_DFP#11]
Device has MPU present in the pdsc:
https://github.com/ARM-software/Cortex_DFP/blob/e663403547b77cf4191a52af5d2931eae3934166/ARM.Cortex_DFP.pdsc#L62-L68

While in the device header
https://github.com/ARM-software/Cortex_DFP/blob/e663403547b77cf4191a52af5d2931eae3934166/Device/ARMCM0plus/Include/ARMCM0plus.h#L92-L98
the __MPU_PRESENT define is 0.

**Comment by ghost** [comment]
Then the device header is wrong.

**Comment by ghost** [comment]
Hello @VladimirUmek, I  updated the device header. Please check if it is ok now.

**Comment by VladimirUmek** [comment]
Thank you for the quick fix!
