### ISSUE TITLE
Specified device not found when upgrading to CMSIS 6

### ISSUE THREAD

**Issue by omarArm** [ARM-software/Cortex_DFP#9]
Problem:

I upgraded my the packs being used in my project from CMSIS@5.9.0 to CMSIS@6.0.0 without changing anything else in the project, all of a sudden I started receiving this error

error csolution: specified device '<Decive Name>' was not found among the installed packs.
use 'cpackget' utility to install software packs.
  cpackget add Vendor.PackName --pack-root ./Path/Packs
error csolution: processing context '<Context>' failed

Solution:

In order to fix the error, the <Device Name> should be updated from the old CMSIS@5.9.0 supported names to the new CMSIS 6.0.0 names. The new names are available in this repo under the "Device" folder, could be found in this [link](https://github.com/ARM-software/Cortex_DFP/tree/main/Device). Also, the migration guide could be found [here](https://learn.arm.com/learning-paths/microcontrollers/project-migration-cmsis-v6/device_mapping/)

**Comment by KeilChris** [comment]
Can you check the migration guide, please? This is mentioned here: https://learn.arm.com/learning-paths/microcontrollers/project-migration-cmsis-v6/device_mapping/

**Comment by omarArm** [comment]
thank you, that clarifies it more
